"""技能包：导入各技能以触发 @skill 注册。"""
from flowmind.skills import alibaba_listing_generate  # noqa: F401
from flowmind.skills import alibaba_product_list  # noqa: F401
from flowmind.skills import alibaba_product_post  # noqa: F401
from flowmind.skills import alibaba_product_recommend  # noqa: F401
from flowmind.skills import b2b_channel_verify  # noqa: F401
from flowmind.skills import b2b_daily_digest  # noqa: F401
from flowmind.skills import b2b_keyword_trends  # noqa: F401
from flowmind.skills import b2b_longtail_keywords  # noqa: F401
from flowmind.skills import b2b_push_feishu  # noqa: F401
from flowmind.skills import b2b_push_wecom  # noqa: F401
from flowmind.skills import content_audit  # noqa: F401
from flowmind.skills import content_copywrite  # noqa: F401
from flowmind.skills import content_hot_topics  # noqa: F401
from flowmind.skills import content_idea_design  # noqa: F401
from flowmind.skills import content_image_gen  # noqa: F401
from flowmind.skills import content_publish_check  # noqa: F401
from flowmind.skills import content_wechat_e2e  # noqa: F401
from flowmind.skills import content_wechat_publish  # noqa: F401
from flowmind.skills import content_web_fetch  # noqa: F401
from flowmind.skills import content_xhs_draft  # noqa: F401
from flowmind.skills import content_xhs_e2e  # noqa: F401
from flowmind.skills import crawler_deadlink  # noqa: F401
from flowmind.skills import crawler_sentiment  # noqa: F401
from flowmind.skills import crawler_viral  # noqa: F401
from flowmind.skills import content_crawler_suite  # noqa: F401
from flowmind.skills import feishu_kb  # noqa: F401
from flowmind.skills import image_prompt_reverse  # noqa: F401
from flowmind.skills import inventory_risk  # noqa: F401
from flowmind.skills import localize_batch      # noqa: F401
from flowmind.skills import localize_cancel     # noqa: F401
from flowmind.skills import localize_download   # noqa: F401
from flowmind.skills import localize_retry      # noqa: F401
from flowmind.skills import localize_status     # noqa: F401
from flowmind.skills import localize_video      # noqa: F401
from flowmind.skills import marketing_image_gen  # noqa: F401
